const fs = require("fs");
const path = require("path");

const rules = [
  {
    id: "auth",
    points: 22,
    level: "bad",
    title: "Authentication or permissions",
    pattern: /auth|token|session|jwt|oauth|permission|role|admin|password/i,
    detail: "Touches access control, sessions, roles, or credentials."
  },
  {
    id: "payment",
    points: 20,
    level: "bad",
    title: "Payments or billing",
    pattern: /payment|billing|invoice|stripe|checkout|refund|price|subscription/i,
    detail: "Impacts money movement, billing, refunds, or pricing."
  },
  {
    id: "database",
    points: 18,
    level: "bad",
    title: "Database or migrations",
    pattern: /migration|schema|alter table|drop table|db\.|select \*|insert into|delete from|update .+ set/i,
    detail: "May affect persistent data, schema, or data integrity."
  },
  {
    id: "secrets",
    points: 30,
    level: "bad",
    title: "Possible secret exposure",
    pattern: /api[_-]?key|secret|private[_-]?key|bearer |password\s*=|token\s*=|AKIA[0-9A-Z]{16}/i,
    detail: "Contains patterns that look like secrets, tokens, or credentials."
  },
  {
    id: "injection",
    points: 24,
    level: "bad",
    title: "Injection risk",
    pattern: /query\(`|exec\(|eval\(|innerHTML|dangerouslySetInnerHTML|SELECT .+\$\{|WHERE .+\$\{/i,
    detail: "Shows dynamic execution, raw HTML, or interpolated SQL patterns."
  },
  {
    id: "tests",
    points: -18,
    level: "ok",
    title: "Tests included",
    pattern: /(__tests__|[\/\\][^\/\\]*(test|spec)\.[jt]sx?$|describe\(|it\(|expect\(|pytest|jest|vitest|unittest)/im,
    detail: "Includes evidence of automated validation."
  },
  {
    id: "config",
    points: 12,
    level: "warn",
    title: "Configuration or deployment",
    pattern: /dockerfile|\.github\/workflows|ci\.yml|env|config|deploy|kubernetes|terraform/i,
    detail: "Changes runtime, CI, deployment, or environment behavior."
  },
  {
    id: "large",
    points: 16,
    level: "warn",
    title: "Large change",
    check: ({ text }) => text.split("\n").length > 220,
    detail: "The diff is large enough to make shallow review risky."
  },
  {
    id: "no-tests",
    points: 16,
    level: "warn",
    title: "No visible tests",
    check: ({ text }) => !/(__tests__|[\/\\][^\/\\]*(test|spec)\.[jt]sx?$|describe\(|it\(|expect\(|pytest|jest|vitest|unittest)/im.test(text),
    detail: "No clear test files or assertions were detected in the diff."
  },
  {
    id: "generated",
    points: 10,
    level: "warn",
    title: "AI-generated marker",
    pattern: /generated by|co-authored-by:.*bot|codex|claude|cursor|copilot/i,
    detail: "The PR appears to include an AI-generated marker or agent reference."
  }
];

async function main() {
  const failThreshold = readNumber("INPUT_FAIL_THRESHOLD", 70);
  const warnThreshold = readNumber("INPUT_WARN_THRESHOLD", 42);
  const shouldComment = readBool("INPUT_COMMENT", true);
  const failOnBlocked = readBool("INPUT_FAIL_ON_BLOCKED", true);

  const context = readContext();
  const diff = await loadDiff(context);
  const result = analyze(diff, { failThreshold, warnThreshold });
  const comment = buildComment(result, context);
  const commentFile = writeComment(comment);

  setOutput("score", String(result.score));
  setOutput("decision", result.decision);
  setOutput("comment-file", commentFile);

  console.log(comment);

  if (shouldComment && context.pullNumber && process.env.INPUT_GITHUB_TOKEN) {
    await upsertPullRequestComment(context, comment);
  } else if (shouldComment && context.pullNumber) {
    console.log("Skipping PR comment because INPUT_GITHUB_TOKEN was not provided.");
  }

  if (failOnBlocked && result.decision === "blocked") {
    process.exitCode = 1;
  }
}

function readNumber(name, fallback) {
  const raw = process.env[name];
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function readBool(name, fallback) {
  const raw = process.env[name];
  if (raw === undefined || raw === "") return fallback;
  return ["1", "true", "yes", "on"].includes(raw.toLowerCase());
}

function readContext() {
  const eventPath = process.env.GITHUB_EVENT_PATH;
  const event = eventPath && fs.existsSync(eventPath)
    ? JSON.parse(fs.readFileSync(eventPath, "utf8"))
    : {};

  const repository = process.env.GITHUB_REPOSITORY || event.repository?.full_name || "";
  const [owner, repo] = repository.split("/");
  const pullNumber = event.pull_request?.number || event.number || "";

  return {
    event,
    owner,
    repo,
    pullNumber,
    serverUrl: process.env.GITHUB_SERVER_URL || "https://github.com",
    runId: process.env.GITHUB_RUN_ID || ""
  };
}

async function loadDiff(context) {
  const diffFile = process.env.INPUT_DIFF_FILE;
  if (diffFile) {
    const resolved = path.resolve(process.cwd(), diffFile);
    return fs.readFileSync(resolved, "utf8");
  }

  if (!context.owner || !context.repo || !context.pullNumber) {
    throw new Error("MergeProof needs a diff-file input or a pull_request GitHub event.");
  }

  const token = process.env.INPUT_GITHUB_TOKEN;
  if (!token) {
    throw new Error("MergeProof needs github-token to fetch the pull request diff.");
  }

  const url = `https://api.github.com/repos/${context.owner}/${context.repo}/pulls/${context.pullNumber}`;
  const response = await fetch(url, {
    headers: {
      Accept: "application/vnd.github.v3.diff",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "mergeproof-action"
    }
  });

  if (!response.ok) {
    throw new Error(`Could not fetch PR diff: ${response.status} ${await response.text()}`);
  }

  return response.text();
}

function analyze(text, { failThreshold, warnThreshold }) {
  const matched = rules
    .filter((rule) => rule.check ? rule.check({ text }) : rule.pattern.test(text))
    .map((rule) => ({ ...rule }));

  const rawScore = matched.reduce((sum, rule) => sum + rule.points, 20);
  const score = Math.max(0, Math.min(100, rawScore));

  let decision = "mergeable";
  let summary = "Low risk. Standard review should be enough.";
  let level = "ok";

  if (score >= failThreshold) {
    decision = "blocked";
    summary = "High risk. Do not merge until the required evidence is added.";
    level = "bad";
  } else if (score >= warnThreshold) {
    decision = "needs_human_review";
    summary = "Medium risk. A human owner should review this before merge.";
    level = "warn";
  }

  return {
    score,
    decision,
    summary,
    level,
    signals: matched,
    checks: buildChecks(matched, score, { failThreshold, warnThreshold })
  };
}

function buildChecks(signals, score, thresholds) {
  const ids = new Set(signals.map((signal) => signal.id));
  const checks = [
    {
      level: ids.has("tests") ? "ok" : "warn",
      title: ids.has("tests") ? "Keep tests required" : "Add minimum tests",
      detail: ids.has("tests")
        ? "Tests were detected. Keep them passing as a merge condition."
        : "Add coverage for the main happy path, failure path, and regression risk."
    },
    {
      level: score >= thresholds.warnThreshold ? "warn" : "ok",
      title: "Assign area owner",
      detail: score >= thresholds.warnThreshold
        ? "Use a reviewer who owns or deeply knows the touched module."
        : "A standard reviewer should be enough unless local policy says otherwise."
    }
  ];

  if (ids.has("auth")) {
    checks.push({
      level: "bad",
      title: "Validate permissions",
      detail: "Test unauthenticated, normal user, admin, expired token, and forbidden access cases."
    });
  }

  if (ids.has("payment")) {
    checks.push({
      level: "bad",
      title: "Validate money flow",
      detail: "Confirm idempotency, retry behavior, webhooks, totals, refunds, and rounding."
    });
  }

  if (ids.has("database")) {
    checks.push({
      level: "bad",
      title: "Add rollback plan",
      detail: "Verify reversible migration, backup path, and compatibility with existing data."
    });
  }

  if (ids.has("secrets")) {
    checks.push({
      level: "bad",
      title: "Remove and rotate secrets",
      detail: "Remove any embedded credentials and rotate anything that may have been exposed."
    });
  }

  if (ids.has("injection")) {
    checks.push({
      level: "bad",
      title: "Harden dynamic execution",
      detail: "Use parameterized queries, safe render paths, and avoid eval or shell execution."
    });
  }

  if (ids.has("config")) {
    checks.push({
      level: "warn",
      title: "Verify environment impact",
      detail: "Confirm CI, deploy, secrets, and runtime config changes in a staging-like path."
    });
  }

  return checks;
}

function buildComment(result, context) {
  const label = result.level === "bad" ? "[BLOCKED]" : result.level === "warn" ? "[REVIEW]" : "[OK]";
  const signals = result.signals.length
    ? result.signals.map((signal) => `- **${signal.title}**: ${signal.detail}`).join("\n")
    : "- No strong risk signals detected.";

  const checks = result.checks
    .map((check) => `- **${check.title}**: ${check.detail}`)
    .join("\n");

  const runLink = context.runId && context.owner && context.repo
    ? `\n\n[Workflow run](${context.serverUrl}/${context.owner}/${context.repo}/actions/runs/${context.runId})`
    : "";

  return `<!-- mergeproof-comment -->
## ${label} MergeProof review

**Decision:** \`${result.decision}\`  
**Risk score:** \`${result.score}/100\`

${result.summary}

### Risk signals
${signals}

### Required before merge
${checks}
${runLink}
`;
}

function writeComment(comment) {
  const outputDir = process.env.RUNNER_TEMP || process.cwd();
  const file = path.join(outputDir, "mergeproof-comment.md");
  fs.writeFileSync(file, comment);
  return file;
}

function setOutput(name, value) {
  const outputPath = process.env.GITHUB_OUTPUT;
  if (outputPath) {
    fs.appendFileSync(outputPath, `${name}=${value}\n`);
  } else {
    console.log(`${name}=${value}`);
  }
}

async function upsertPullRequestComment(context, body) {
  const token = process.env.INPUT_GITHUB_TOKEN;
  const baseUrl = `https://api.github.com/repos/${context.owner}/${context.repo}/issues/${context.pullNumber}/comments`;
  const headers = {
    Accept: "application/vnd.github+json",
    Authorization: `Bearer ${token}`,
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "mergeproof-action"
  };

  const listResponse = await fetch(`${baseUrl}?per_page=100`, { headers });
  if (!listResponse.ok) {
    throw new Error(`Could not list PR comments: ${listResponse.status} ${await listResponse.text()}`);
  }

  const comments = await listResponse.json();
  const existing = comments.find((comment) => comment.body?.includes("<!-- mergeproof-comment -->"));

  if (existing) {
    const updateResponse = await fetch(existing.url, {
      method: "PATCH",
      headers: { ...headers, "Content-Type": "application/json" },
      body: JSON.stringify({ body })
    });
    if (!updateResponse.ok) {
      throw new Error(`Could not update PR comment: ${updateResponse.status} ${await updateResponse.text()}`);
    }
    return;
  }

  const createResponse = await fetch(baseUrl, {
    method: "POST",
    headers: { ...headers, "Content-Type": "application/json" },
    body: JSON.stringify({ body })
  });

  if (!createResponse.ok) {
    throw new Error(`Could not create PR comment: ${createResponse.status} ${await createResponse.text()}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
